import type { Metadata } from "next"
import "./globals.css";
import Header from "@components/components/Header";

export const metadata: Metadata = {
  title: "TaeHyun's Devlog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
