import type { Metadata } from "next"
import "./globals.css";
import Header from "@components/components/Header";
import NavBar from "@components/components/NavBar";

export const metadata: Metadata = {
  title: "TaeHyun's Devlog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col h-screen">
        <Header />
        <div className="flex flex-1 max-w-[90rem] mx-auto w-full pt-[65px]">
          <NavBar />
          {children}
        </div>
      </body>
    </html>
  );
}
